
#ifndef COMMUNICATION
#define COMMUNICATION

typedef enum {
	ABSENCE_CARTON,
	PIECES_DEFECTUEUSES,
	PANNE_IMPRIMANTE,
	FILE_CARTONS_PLEINE,
	ABSENCE_PALETTE,
	PIECES_TIMEOUT,
	ERREUR_FILMAGE
} CODE_ERREUR;

typedef enum {
	CARTON_DEBUT,
	PIECE_DANS_CARTON,
	CARTON_PLEIN,
	CARTON_IMPRIME,
	CARTON_DANS_PALETTE,
	PALETTE_PLEINE,
	COMMANDE_EXPEDIEE,
	CLAPET_OUVERT,
	CLAPET_FERME,
	ERREUR_REPAREE
} CODE_EVENEMENT;

void erreur(CODE_ERREUR code);

void message(CODE_EVENEMENT code, int val1, int val2, int val3);

void log(CODE_EVENEMENT code, int val1, int val2, int val3);

#endif
